- name: Setup Database Server
  hosts: web
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes
