- name: Setup Full Stack Environment (Web + DB)
  hosts: web
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    # NGINX
    - name: Install nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy index.html
      copy:
        content: "<h1>Full Stack Environment: NGINX + PostgreSQL is ready!</h1>"
        dest: /var/www/html/index.html

    # PostgreSQL
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes
